LyricManagement/Models/ErrorViewModel.cs
using System;

namespace LyricManagement.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LyricManagement/Models/Lyrics/LyricViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LyricManagement.Models.Lyrics
{
    public class LyricViewModel
    {
        public int Id  { get; set; }
        public string Title { get; set; }
        public string image { get; set; }
        public string Artist { get; set; }
        public string Views { get; set; }
        public string Year { get; set; }
        public string Lyrics { get; set; }

    }
}

LyricManagement/Models/Lyrics/LyricsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LyricManagement.Models.Lyrics
{
    public class LyricsModel
    {
        public IEnumerable<LyricViewModel> Lyrics { get; set; }
    }
}

LyricManagement/Controllers/ExtensionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LyricData;
using LyricData.Extensions;
using LyricData.Models;
using Microsoft.AspNetCore.Mvc;

namespace LyricManagement.Controllers
{
    public class ExtensionController : Controller
    {
        private readonly ILyrics _cc;

        public ExtensionController(ILyrics cc)
        {
            _cc = cc;
        }
        public IActionResult Index()
        {
            var data = _cc.GetAllLyric();
            foreach (var item in data)
            {
                ViewModels ext = new ViewModels()
                {

                    Data = new List<SongLyric>()
                {
                   new SongLyric{Id=item.Id },
                }
                };
                ViewBag.total = ext.Totaldata();

            }



          


            return View();
        }
    }
}

LyricManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LyricManagement.Models;

namespace LyricManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LyricManagement/Controllers/SongLyricsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using LyricData;
using LyricData.Extensions;
using LyricData.Models;
using LyricManagement.Models;
using LyricManagement.Models.Lyrics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LyricManagement.Controllers
{
    public class SongLyricsController : Controller
    {
        private readonly ILyrics _cc;
      
        public SongLyricsController(ILyrics cc)
        {
            _cc = cc;
        }
      
        public IActionResult Index()
        {
            var result = _cc.GetAllLyric().ToList();
            return View(result);
        }
        public IActionResult Home()
        {
            return View();
        }
        public IActionResult Data()
        {
            var assetModels = _cc.GetAllLyric().ToList();
            return View(assetModels);
        }

     
       
        public IActionResult Detail(int id)
        {
            var song = _cc.GetById(id);
            if (song == null)
            {

                return RedirectToAction("nofound");

            }
           


            
            return View(song);
        }
        public async Task<IActionResult> Search(string word, int? pageNumber, string sortOrder, string currentFilter)
        {

          
            var data = _cc.GetAllLyric();
            Stopwatch sw = Stopwatch.StartNew();

            ViewData["CurrentSort"] = sortOrder;
          
            if (word != null)
            {
                pageNumber = 1;
            }
            else
            {
                word = currentFilter;
            }
            ViewData["CurrentFilter"] = word;
           
            var song = _cc.GetAll(word);
           
           
            int pageSize = 10;
            ViewBag.found = song.Count();

         
            sw.Stop();
            ViewBag.time = sw.Elapsed.TotalSeconds;
            foreach (var item in data)
            {
                ViewModels ext = new ViewModels()
                {

                    Data = new List<SongLyric>()
                {
                   new SongLyric{Id=item.Id },
                }
                };
                ///////extension////method//////
                ViewBag.total = ext.Totaldata();

            }




            return View(await PaginatedList<SongLyric>.CreateAsync(song.AsNoTracking(), pageNumber ?? 1, pageSize));
          
         
        }
        public IActionResult Delete(int id)
        {

            var data = _cc.GetById(id);
            if (data == null)
            {
                return RedirectToAction("nofound");

            }
            
            return View(data);

        }
      
        public IActionResult DeleteConfirm(int id)
        {
            _cc.delete(id);
            return RedirectToAction("Search");
        }
           

        [HttpGet]
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public IActionResult Create( SongLyric song)
        {
            if (ModelState.IsValid)
            {
                _cc.Add(song);
                return RedirectToAction("Search");
            }
            return View(song);

        }
        public IActionResult Edit(int id)
        {
            var data = _cc.GetById(id);
            if (data == null)
            {
                return RedirectToAction("nofound");

            }
            return View(data);
        }
        [HttpPost]
        public IActionResult Edit(int id, SongLyric song)
        {
            if (ModelState.IsValid)
            {
                _cc.update(song);
                return RedirectToAction("Data");
            }
            return View(song);

        }
        public IActionResult nofound()
        {
            return View();
        }



    }
}

LyricManagement/Views/Extension/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>@ViewBag.total</h1>

LyricManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LyricManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LyricManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="SongLyrics" asp-action="Home">LyricManagement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SongLyrics" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            <div clsaa="div" style="height:200px;">

            </div>
            &copy; 2020 - LyricManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">By-Mukesh Mahato</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LyricManagement/Views/SongLyrics/Create.cshtml
@model LyricData.Models.SongLyric

@{
    ViewData["Title"] = "Create";
}



<h4>SongLyric</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
                <div class="form-group">
                 
                    <input asp-for="Title" class="form-control" placeholder="Title" required/>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input asp-for="Artist" class="form-control" placeholder="Artist/Singer  Name" required/>
                    <span asp-validation-for="Artist" class="text-danger"></span>
                </div>
                <div class="form-group">
                 
                    <input asp-for="Image" class="form-control" placeholder="ImageUrl" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>

            
            
                <div class="form-group">
                
                    <input asp-for="Views" class="form-control" placeholder="Views" required />
                    <span asp-validation-for="Views" class="text-danger"></span>
                </div>
                <div class="form-group">
                  
                    <input asp-for="Year" class="form-control" placeholder="Year" required/>
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
                <div class="form-group">
               
                    <input asp-for="Lyrics" class="form-control" placeholder="Lyrics" required/>
                    <span asp-validation-for="Lyrics" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>

    
           
           
        </form>
    </div>
</div>

<div>
    <a asp-action="Search">Back to search</a>

</div>

LyricManagement/Views/SongLyrics/Data.cshtml
@model IEnumerable<LyricData.Models.SongLyric>

@{
    ViewData["Title"] = "Data";
}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">






<title>Page Title</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link href="~/css/main.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="./css/main.css">

<div class="container">
    <div id="cover">
        <form method="get" action="Search">
            <div class="tb">
                <div class="td"><input type="text" placeholder="Search" name="word" required></div>
                <div class="td" id="s-cover">
                    <button type="submit">
                        <div id="s-circle"></div>
                        <span></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>









@foreach (var item in Model)
{
    <div class="container">
        <div class="header clearfix detailHeading">

        </div>

        <div class="jumbotron">
            <div class="row">

                <div class="col-md-4">
                    <div>
                        <img class="Detail" src="~/Image/photo.jpg" style="height:300px;width:300px;" />
                        @*<img class="detailImage" src="@item.Image" />*@
                    </div>
                </div>
                <div class="col-md-4">
                    <p id="itemTitle"><h2>@item.Title</h2></p>
                    <p id="itemAuthor"><h4>@item.Artist</h4></p>
                    <p id="itemStatus"><h6><span><i class="fa ">Year:</i>@item.Year</span></h6><h6><i class="fa fa-eye">@item.Views</i></h6></p>
                    <br />
                    <br />
                    <div>
                        <b>Lyrics</b>
                        <br />
                        @if (item.Lyrics.Length > 150)
                        {
                            @item.Lyrics.Substring(0, 150)
                        }
                        else
                            @item.Lyrics
                    </div>
                    <p><a asp-action="Details" asp-route-id="@item.Id">Details..</a>|<a asp-action="Delete" asp-route-id="@item.Id">Delete</a></p>
                </div>
            </div>
        </div>
    </div>
}

LyricManagement/Views/SongLyrics/Delete.cshtml
@model LyricData.Models.SongLyric

@{
    ViewData["Title"] = "";
}



<h3>Are you sure you want to delete this?</h3>
<div>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="container">
        <div class="jumbotron">
            <div class="row">

                <div class="col-md-4">
                    <div>
                        <img class="Detail" src="~/Image/photo.jpg" style="height:300px;width:300px;" />
                        @*<img class="detailImage" src="@item.Image" />*@
                    </div>
                </div>
                <div class="col-md-4">
                    <p id="itemTitle"><h2>@Model.Title</h2></p>
                    <p id="itemAuthor"><h4>@Model.Artist</h4></p>
                    <p id="itemStatus"><h6><span><i class="fa ">Year:</i>@Model.Year</span></h6><h6><i class="fa fa-eye">@Model.Views</i></h6></p>

                    <br />
                    <br />
                    <div>
                        <b>Lyrics</b>
                        <br />
                        <p id="itemType">@Model.Lyrics</p>

                    </div>
                    <p>
                        <a asp-action="DeleteConfirm" asp-route-id="@Model.Id">Delete..</a>|
                        <a asp-action="Edit" asp-route-id="@Model.Id">Edit..</a>|
                        <a asp-action="Data" asp-route-id="@Model.Id">Back..</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div>
       
       
    </div>

   
</div>

LyricManagement/Views/SongLyrics/Detail.cshtml
@model LyricData.Models.SongLyric

@{
    ViewData["Title"] = "";
}

<h2 class="text-muted"> Library</h2>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="container">
    <div class="jumbotron">
        <div class="row">

            <div class="col-md-4">
                <div>
                    <img class="Detail" src="~/Image/photo.jpg" style="height:300px;width:300px;" />
                    @*<img class="detailImage" src="@item.Image" />*@
                </div>
            </div>
            <div class="col-md-4">
                <p id="itemTitle"><h2>@Model.Title</h2></p>
                <p id="itemAuthor"><h4>@Model.Artist</h4></p>
                <p id="itemStatus"><h6><span><i class="fa ">Year:</i>@Model.Year</span></h6><h6><i class="fa fa-eye">@Model.Views</i></h6></p>
               
                <br />
                <br />
                <div>
                    <b>Lyrics</b>
                    <br />
                    <p id="itemType">@Model.Lyrics</p>
                        
                </div>
            </div>
        </div>
    </div>
</div>

LyricManagement/Views/SongLyrics/Edit.cshtml
@model LyricData.Models.SongLyric

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SongLyric</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Views" class="control-label"></label>
                <input asp-for="Views" class="form-control" />
                <span asp-validation-for="Views" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lyrics" class="control-label"></label>
                <input asp-for="Lyrics" class="form-control" />
                <span asp-validation-for="Lyrics" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Home">Back to List</a>
</div>

LyricManagement/Views/SongLyrics/Home.cshtml
@{
    ViewData["Title"] = "Home";

}


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="./css/main.css">
<link href="~/css/style.css" rel="stylesheet" />

<div class="container">
    <div class="head">
        <p>
            Search Lyrics...
        </p>
    </div>

    <div id="cover">
        <form    method="get" action="Task/SongLyrics/Search">
            <div class="tb">
                <div class="td">
                <input type="text" placeholder="Search" name="word" required></div>
                <div class="td" id="s-cover">
                    <button type="submit">
                        <div id="s-circle"></div>
                        <span></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<footer class="border-top footer text-muted">
    <div class="container">
        <div clsaa="div" style="height:434px;">

        </div>
        &copy; 2020 - LyricManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">By-Mukesh Mahato</a>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

LyricManagement/Views/SongLyrics/Index.cshtml
@model IEnumerable<LyricData.Models.SongLyric>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Views)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lyrics)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Views)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lyrics)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

LyricManagement/Views/SongLyrics/Search.cshtml
@using LyricData.Extensions;

@model PaginatedList<LyricData.Models.SongLyric>

@{
    ViewData["Title"] = "Search";
}



<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">






    <title>Page Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="~/css/main.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="./css/main.css">

    <div class="container">
        <div id="cover">
            <form method="get" action="Search" >
                <div class="tb">
                    <div class="td"><input type="text" placeholder="Search" name="word" required></div>
                    <div class="td" id="s-cover">
                        <button type="submit">
                            <div id="s-circle"></div>
                            <span></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

 






<div class="container">
    <br />
    <br />
    <div class="space" style="height:20%;margin-right:30px;margin: 44px auto;
    text-align: center;">
        <p><h4>Welcome To Lyrics Gallery</h4> </p>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div>
                <h6> ExecutionTime:@ViewBag.time</h6>
            </div>
        </div>
        <div class="col-md-4">
            <h6> Total Match:@ViewBag.found</h6>
        </div>
        <div class="col-md-4">
            <h6> Total Data:@ViewBag.total</h6>
        </div>
    </div>
</div>
@foreach (var item in Model)
{
    <div class="container">



        <div class="jumbotron">
            <div class="row">

                <div class="col-md-4">
                    <div>

                        @if (item.Image == null)
                        {
                            <img class="Detail" src="~/Image/photo.jpg" style="height:300px;width:300px;" />
                        }
                        else
                        {
                       <img class="Detail" src="@item.Image" style="height:300px;width:300px;" />
                        }
                        
                        @*<img class="detailImage" src="@item.Image" />*@
                    </div>
                </div>
                <div class="col-md-4">
                    <p id="itemTitle"><h2>@item.Title</h2></p>
                    <p id="itemAuthor"><h4>@item.Artist</h4></p>
                    <p id="itemStatus"><h6><span><i class="fa ">Year:</i>@item.Year</span></h6><h6><i class="fa fa-eye">@item.Views</i></h6></p>
                    <br />
                    <br />
                    <div>
                        <b>Lyrics</b>
                        <br />
                        @if (item.Lyrics.Length > 150)
                        {
                            @item.Lyrics.Substring(0, 150)
                        }
                        else
                            @item.Lyrics
                    </div>
                    <a asp-action="Detail" asp-route-id="@item.Id">Details..</a>
                </div>
            </div>
        </div>
    </div>
}





@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";

    var nextDisabled = !Model.HasNextPage ? "disabled" : "";

}

<a asp-action="Search"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="abc+ @(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">

    Previous

</a>

<a asp-action="Search"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">

    Next

</a>

LyricManagement/Views/SongLyrics/nofound.cshtml
@{
    ViewData["Title"] = "nofound";
}

<h1>Song Doesnot Exist</h1>